
# This is an example of the cert-generation job you'd run.

apiVersion: v1
kind: Pod
metadata:
  name: letsencrypt-generate-certs
  labels:
    app: letsencrypt-generate-certs
spec:
  restartPolicy: Never
  containers:
  - name: letsencrypt-generate-certs
    image: docker.io/iameli/kubernetes-letsencrypt
    imagePullPolicy: Always
    command:
      - bash
      - -c
      - "mkdir webroot && cd webroot && python -m SimpleHTTPServer 80"
    # args:
    #   - api.dandiprat.industries
    #   - www.dandiprat.industries
    #   - jenkins.dandiprat.industries
    #   - dandiprat.industries
    env:
      - name: tos
        value: "true"
      - name: country
        value: US
      - name: state
        value: Washington
      - name: town
        value: Seattle
      - name: organization
        value: Dandiprat Industries
      - name: email
        value: eli@streamprov.com
      - name: secretName
        value: letsencrypt-ssl
      # - name: acmeServer
      #   value: https://acme-staging.api.letsencrypt.org/directory
      - name: namespace
        value: default
