
# This is an example of the cert-generation job you'd run.

apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: letsencrypt-generate-certs
spec:
  selector:
    matchLabels:
      app: letsencrypt-generate-certs
  template:
    metadata:
      name: letsencrypt-generate-certs
      labels:
        app: letsencrypt-generate-certs
    spec:
      restartPolicy: Never
      containers:
      - name: letsencrypt-generate-certs
        image: docker.io/iameli/kubernetes-letsencrypt
        imagePullPolicy: Always
        # command:
        #   - tail
        #   - -f
        #   - /dev/null
        args:
          - api.dandiprat.industries
          - www.dandiprat.industries
          - jenkins.dandiprat.industries
        env:
          - name: tos
            value: "true"
          - name: country
            value: US
          - name: state
            value: Washington
          - name: town
            value: Seattle
          - name: organization
            value: Dandiprat Industries
          - name: email
            value: eli@streamprov.com
          - name: secretName
            value: letsencrypt-ssl
          # - name: acmeServer
          #   value: https://acme-staging.api.letsencrypt.org/directory
          - name: namespace
            value: default
